# easy,linuxのタグが付いたランナー上で動かす。そのときのDockerのイメージは
# node:ltsを使用する
default:
  image: node:lts
  tags:
    - easy
    - linux

# ランナーで本処理が走る前に行っておく前処理。ここでは依存パッケージをインストールし、
# スライドの画像をフォルダごとGitLab Pagesで公開する先のフォルダにコピーするための
# rsyncコマンドをインストールしている
before_script:
  - npm ci
  - apt-get update
  - apt-get install -y --no-install-recommends rsync

# 本処理。GitLab Pagesで公開する場合は、ジョブの名前がpagesでないといけない。
# artifactsで記述したパス下のファイルを公開することになる。
#
# ここではpackage.jsonに書かれたgen:all処理を実行し、処理中に生成された
# ファイル群(アーティファクト)はpublicフォルダに保存する処理を行っている
pages:
  script:
    - npm run gen:all
  artifacts:
    paths:
      # 以下のページによるとGitLab Pagesで公開するにはフォルダ名が public
      # でないといけないようなので注意
      # https://docs.gitlab.com/ee/user/project/pages/getting_started/pages_ui.html
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
